# Generated by Django 6.0.6 on 2026-07-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('pais', 'apelativo')},
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(condition=models.Q(('edad__gte', 18)), name='edad_mayor_18'),
        ),
    ]
