# Generated by Django 6.0.6 on 2026-07-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_empleados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='empleao',
            new_name='empleado',
        ),
    ]
