# Generated by Django 6.0.6 on 2026-07-20 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_empleao_empleados_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.persona')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            bases=('home.persona',),
        ),
    ]
