# Generated by Django 6.0.6 on 2026-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lector',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lector',
            name='nombres',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
